# _config.yml


plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes"
 
title: 1DevEnough
#description: 1인 개발을 위한 모든 것

logo: "/assets/images/index/logo.png"
